export const mapFieldName = {
  "Claim ID": "claim_id",
  "Subscriber ID": "subscriber_id",
  "Member Sequence": "member_sequence",
  "Claim Status": "claim_status",
  Billed: "billed",
  Allowed: "allowed",
  Paid: "paid",
  "Payment Status Date": "payment_status_date",
  "Service Date": "service_date",
  "Received Date": "received_date",
  "Entry Date": "entry_date",
  "Processed Date": "processed_date",
  "Paid Date": "paid_date",
  "Payment Status": "payment_status",
  "Group Name": "group_name",
  "Group ID": "group_id",
  "Division Name": "division_name",
  "Division ID": "division_id",
  Plan: "plan",
  "Plan ID": "plan_id",
  "Place of Service": "place_of_service",
  "Claim Type": "claim_type",
  "Procedure Code": "procedure_code",
  "Member Gender": "member_gender",
  "Provider ID": "provider_id",
  "Provider Name": "provider_name",
};

